### ISSUE TITLE
Error: while migrating OWLAirdrop

### ISSUE THREAD

**Issue by amitkot** [gnosis/dx-contracts#61]
I’m seeing this error when migrating as part of running the tests for a dutchx market maker contract I am working on.

It happens after a couple of times that I run the tests, and after I restart ganache-cli it works fine again.

```
Deploying WETH contract, because the network "development" doesn't have any WETH address configured
Link Math lib into EtherToken
Deploy EtherToken
Deploying WETH contract, because the network "development" doesn't have any WETH address configured
Link Math lib into EtherToken
Deploy EtherToken
Link Math lib to TokenGNO
Deploy TokenGNO:
  - Owner: 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1
  - Initial token amount: 10000000
Deploying WETH contract, because the network "development" doesn't have any WETH address configured
Link Math lib into EtherToken
Deploy EtherToken
Deploying WETH contract, because the network "development" doesn't have any WETH address configured
Link Math lib into EtherToken
Deploy EtherToken
Link Math lib to TokenGNO
Deploy TokenGNO:
  - Owner: 0x90F8bf6A479f320ead074411a4B0e7944Ea8c9C1
  - Initial token amount: 10000000
Link Math lib to TokenOWL and TokenOWLProxy
Deploy TokenOWL
Deploy TokenOWLProxy
  - owl master address: 0x4b1b219219b1de97F84D61e1dd9755b2A0b6811E
Deploy OWLAirdrop:
	 OWL proxy address: 0xeAf4cf672658D835574e03D4ad87cD82A93957c5
	 GNO address: 0x7578895011A9f684BFb065238886e84638De671a
	 End time: Tue Jan 08 2019 16:47:15 GMT+0200 (IST)
Error: while migrating OWLAirdrop: Returned error: VM Exception while processing transaction: revert The end time cannot be in the past -- Reason given: The end time cannot be in the past.
    at /Users/amit/src/kyber/dutchx/dutchx-market-maker/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:361:1
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

```
$ truffle version
Truffle v5.0.0-beta.1 (core: 5.0.0-beta.1)
```

**Comment by dasanra** [comment]
This issue was related to truffle-4/truffle-5 migration. Should be solved in current stable versions v2.0.0 and above:

https://github.com/gnosis/dx-contracts/tree/v2.0.0

**Comment by gorgos** [comment]
I am still seeing this issue in v2.0.0.

@dasanra Are you talking about this fix https://github.com/gnosis/owl-token/commit/5b2f9440150dbba622fba30a4eded8b434466f94 ?

I don't think that fixes this issue here. My guess would be that when the ganache time increases more and more, the default of 30 days in the future ([GNO_LOCK_PERIOD_IN_HOURS](https://github.com/gnosis/owl-token/blob/f773af5218dfc30daffc2becff300a559bfebc2d/src/migrations-truffle-5/4_deploy_OWL_airdrop.js#L1)) is not sufficient anymore.
